alter table SALES_ORDER_LINE add constraint FK_SALES_ORDER_LINE_ON_ORDER foreign key (ORDER_ID) references SALES_ORDER(ID);
alter table SALES_ORDER_LINE add constraint FK_SALES_ORDER_LINE_ON_PRODUCT foreign key (PRODUCT_ID) references SALES_PRODUCT(ID);
create index IDX_SALES_ORDER_LINE_ON_ORDER on SALES_ORDER_LINE (ORDER_ID);
create index IDX_SALES_ORDER_LINE_ON_PRODUCT on SALES_ORDER_LINE (PRODUCT_ID);
